version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Instalando dependências do projeto..."
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Iniciando a auditoria de Data Drift..."
      - python monitoramento.py
  post_build:
    commands:
      - echo "Auditoria finalizada com sucesso!"